version: '3'
services:
  django:
    build: .
    volumes:
      - ./advanced_software/introduced_facility:/app
  nginx:
    build: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./advanced_software/introduced_facility:/app
