# Generated by Django 3.2 on 2024-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('nakamozu', '中百舌鳥キャンパス'), ('sugimoto', '杉本キャンパス'), ('morinomiya', '森ノ宮キャンパス'), ('abeno', '阿倍野キャンパス'), ('habikino', '羽曳野キャンパス'), ('rinnkuu', 'りんくうキャンパス')], max_length=100)),
            ],
        ),
    ]
