# Generated by Django 3.2 on 2024-01-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='eng_name',
            field=models.CharField(default='new facility', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.CharField(default='image.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='url',
            field=models.CharField(default='url', max_length=100),
        ),
    ]
